const ACTIONS = {
    APP_INIT_START: 'APP_INIT_START',
    APP_INIT_STOP: 'APP_INIT_STOP',

    GET_TIMERS: 'GET_TIMERS',
    RESORT_TIMERS: 'RESORT_TIMERS',
    ADD_TIMER: 'ADD_TIMER',
    SELECTED_TIMER: 'SELECTED_TIMER',
    PLAY_TIMER: 'PLAY_TIMER',
    PLAY_NEXT_TIMER: 'PLAY_NEXT_TIMER',
    PAUSE_TIMER: 'PAUSE_TIMER',
    STOP_TIMER: 'STOP_TIMER',
    TICK_TIMER: 'TICK_TIMER',
    TICK: 'TICK',

    START_AUDIO: 'START_AUDIO',
    STOP_AUDIO: 'STOP_AUDIO',
};

export {ACTIONS};
export default ACTIONS;
