const ACTIONS = {
    ADD_TIMER: 'ADD_TIMER',
    SELECTED_TIMER: 'SELECTED_TIMER',
    PLAY_TIMER: 'PLAY_TIMER',
    PAUSE_TIMER: 'PAUSE_TIMER',
    STOP_TIMER: 'STOP_TIMER',
    TICK_TIMER: 'TICK_TIMER',

    SET_HEIGHT_NAVBAR: 'SET_HEIGHT_NAVBAR',
    SET_HEIGHT_HEADER: 'SET_HEIGHT_HEADER',
    SET_HEIGHT_FOOTER: 'SET_HEIGHT_FOOTER',
};

export {ACTIONS};
export default ACTIONS;
